std/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns(
    'std.views',
    url(r'^$', 'index', name='std_index'),
    url(r'^underconst/$', 'underconst', name='std_under_construction'),

    url(r'^login/$', 'auth.login', name='std_login'),
    url(r'^login/token/$', 'auth.login_with_token', name='std_login_with_token'),
    url(r'^logout/$', 'auth.logout', name='std_logout'),

    url(r'^edit/', 'profile.edit', name='std_edit'),
    url(r'^profile/','profile.profile',name='std_profile'),
    url(r'^confirm_email/(.+)/','profile.confirm_email'),
    url(r'^regtype/(\d)/$','choose_reg_type',name='std_choose_reg_type'),
    url(r'^regtype/(\d)/confirm/','confirm_reg_type',name='std_confirm_reg_type'),

    url(r'^checkstatus/$','check_internship_status',name='std_checkstatus'),
    url(r'^print_request_form/$','PrintRequestForm',name='std_print_request_form'),

    url(r'^companies/$','company_list',name='std_company_list'),
      
    url(r'^selection/$','company_selection.list',name='std_selection_list'),
    url(r'^selection/select/(\d+)/$','company_selection.select',
        name='std_selection_select'),
    url(r'^selection/deselect/(\d+)/$','company_selection.deselect',
        name='std_selection_deselect'),

    url(r'^company/search/$', 'company.search',
        name='std_company_search'),
    url(r'^company/search/(.+)/$','company.list_by_char',name='std_company_list_by_char'),

    url(r'^self_appl/$', 'company.self_appl_index',
        name='std_self_appl_index'),
    url(r'^self_appl/confirm/$', 'company.self_appl_confirm',
        name='std_self_appl_confirm'),

    url(r'^self_appl/requests/$', 'company.new_request',
        name='std_self_appl_new_company_request'),
    url(r'^self_appl/requests/confirm/(\d+)/', 'company.request_confirm',
        name='std_self_appl_request_confirm'),
    url(r'^self_appl/requests/inactive/$', 'company.inactive_requests',
        name='std_self_appl_inactive_company_requests'),
    url(r'^self_appl/requests/print/(\d+)/$', 'company.print_request',
        name='std_self_appl_request_print'),
    url(r'^self_appl/requests/sending_letter/(\d+)/$', 'company.print_request_sending_letter_pdf',
        name='std_self_appl_print_request_sending_letter'),

    url(r'^self_appl/announcement/print/$', 'company.print_announcement',
        name='std_self_appl_request_print_announcement'),

    url(r'^self_appl/stdsearch/$', 'company.student_search',
        name='std_self_appl_student_search'),
    url(r'^self_appl/name/search/$', 'company.search_by_name_ajax',
        name='std_self_appl_company_search_by_name_ajax'),

    url(r'^self_appl/applications/create/$', 'company.create_direct_application',
        name='std_self_appl_create_application'),
    url(r'^self_appl/applications/update/(\d+)/$', 'company.update_direct_application',
        name='std_self_appl_update_application'),
    url(r'^self_appl/applications/cancel/(\d+)/$', 'company.cancel_direct_application',
        name='std_self_appl_cancel_application'),
    url(r'^self_appl/applications/print/(\d+)/$', 'company.print_direct_application_letter',
        name='std_self_appl_print_application_letter'),
    url(r'^self_appl/applications/verified/$', 'company.list_verified_direct_application_companies',
        name='std_self_appl_list_verified_companies'),
    url(r'^self_appl/applications/sending_letter/(\d+)/$', 'company.print_direct_application_sending_letter_pdf',
        name='std_self_appl_print_application_sending_letter'),
    
    url(r'^print_company_letter/(\d+)/$',
        'print_letter', name='std_print_letter'),

    url(r'^coop/$', 'coop.index',
        name='std_coop_index'),
    url(r'^coop/address/$', 'coop.update_address',
        name='std_coop_address'),

    url(r'^coop/companies/$', 'coop.update_company',
        name='std_coop_create_company'),

    url(r'^coop/companies/(?P<co_op_company_id>\d+)/$', 'coop.update_company',
        name='std_coop_update_company'),
    url(r'^coop/requests/(?P<co_op_company_id>\d+)/$', 'coop.create_request',
        name='std_coop_create_request'),

    url(r'^coop/requests/print/(\d+)/([a-z]+)/$', 'coop.print_request',
        name='std_coop_request_print'),
)

worktraining/urls.py
from django.conf.urls import url, include, patterns
from django.conf import settings

import django.contrib.staticfiles.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import commons.views
import regis.announcement.views
import evaluations.views
import commons.auth_views

urlpatterns = patterns(
    '',
    #(r'^$',
    # 'django.views.generic.simple.direct_to_template',
    # {'template': 'front.html'}),
    url(r'^$', commons.views.index, name='front_page'),

    url(r'^announcement/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_detail,
        name='front_announcement_detail'),
    url(r'^announcement/edit/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_edit,
        name='announcement_edit'),
    url(r'^announcement/index/$',
        regis.announcement.views.list,
        name='announcement_index'),
    url(r'^announcement/create/$',
        regis.announcement.views.announcement_create,
        name='announcement_create'),
    url(r'^announcement/delete/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_delete,
        name='announcement_delete'),
    
    (r'^regis/', include('regis.urls')),
    (r'^std/', include('std.urls')),
    (r'^eval/', include('evaluations.urls')),
    (r'^committee/', include('committee.urls')),
    (r'^commons/', include('commons.urls')),
    (r'^direct/', include('direct_appl.urls')),

    url(r'^ev/(\d+)/(.+)/$',
        evaluations.views.edit_by_company,
        name='short_evaluations_edit_by_company'),


    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # authentication
    url(r'^accounts/login/$', 
        commons.auth_views.login,
        name='admin_login'),
    url(r'^accounts/logout/$', 
        'django.contrib.auth.views.logout',
        { 'next_page': settings.LOGOUT_URL },
        name='admin_logout'),
    url(r'^accounts/login/token/$',
        commons.auth_views.login_user_with_token,
        name='admin_login_token'),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        # Static media (for development)
        (r'^site_media/(?P<path>.*)$',
         django.contrib.staticfiles.views.serve),
    )

std/models.py
# -*- coding: utf-8 -*-
from django.db import models, IntegrityError
from regis.models import Student, Company, Assignment, Receipt, ConfigLetterBase, Department
from commons.models import Configuration
from commons.academia import get_next_worktraining_year
import hashlib
import random
from datetime import datetime
from django.conf import settings

class StudentExtraPassword(models.Model):
    student_id = models.CharField(max_length=15,
                                  verbose_name=u'รหัสนิสิต',
                                  unique=True)
    hashed_password = models.CharField(max_length=128)
    salt = models.CharField(max_length=10)

    @staticmethod
    def set_password_for(student_id, password):
        try:
            passwd = StudentExtraPassword.objects.get(student_id=student_id)
        except StudentExtraPassword.DoesNotExist:
            passwd = StudentExtraPassword(student_id=student_id)

        passwd.salt = str(random.random())[-5:]
        passwd.hashed_password = hashlib.sha1(passwd.salt + password).hexdigest()
        passwd.save()

    @staticmethod
    def check_password_for(student_id, password):
        try:
            passwd = StudentExtraPassword.objects.get(student_id=student_id)
        except StudentExtraPassword.DoesNotExist:
            return False

        try:
            return (passwd.hashed_password == 
                    hashlib.sha1(passwd.salt + password).hexdigest())
        except:
            return False

class StudentTokenNonce(models.Model):
    student_id = models.CharField(max_length=15)
    nonce = models.CharField(max_length=128)

    class Meta:
        unique_together = [['student_id','nonce']]

    @staticmethod
    def check_and_save(student_id, nonce):
        if len(nonce) < 8:
            return False
        
        count = StudentTokenNonce.objects.filter(student_id=student_id,
                                                 nonce=nonce).count()
        if count != 0:
            return False

        n = StudentTokenNonce(student_id=student_id,
                              nonce=nonce)
        try:
            n.save()
            return True
        except:
            return False

    @staticmethod
    def check_token_hash(student_id, nonce, token_hash):
        key = nonce + student_id + settings.TOKEN_SECRET
        key_hash = hashlib.sha1(key).hexdigest()[:20]
        return token_hash == key_hash

    @staticmethod
    def generate_token(student_id, nonce='', secret=''):
        if nonce == '':
            nonce = ''.join([random.choice('0123456789abcdefghijklmnopqrstuvwxyz') for i in range(10)])
        if secret == '':
            secret = settings.TOKEN_SECRET
        key = nonce + student_id + secret
        key_hash = hashlib.sha1(key).hexdigest()[:20]
        return student_id + '_' + nonce + '_' + key_hash


ALP = '0123456789'

class EmailConfirmation(models.Model):
    student = models.OneToOneField(Student, 
                                   related_name='email_confirmation')
    is_confirmed = models.BooleanField()
    requested_at = models.DateTimeField()
    confirmed_at = models.DateTimeField(null=True)
    code = models.CharField(max_length=100,
                            unique=True)

    @staticmethod
    def random_confirmation_code():
        return ''.join([random.choice(ALP) for i in range(20)])

    @staticmethod
    def create_or_update_for(student):
        try:
            confirmation = student.email_confirmation
        except EmailConfirmation.DoesNotExist:
            confirmation = EmailConfirmation()

        confirmation.student = student
        confirmation.is_confirmed = False
        confirmation.requested_at = datetime.now()
        confirmation.confirmed_at = None

        for i in range(10):
            confirmation.code = EmailConfirmation.random_confirmation_code()
            try:
                confirmation.save()
            except IntegrityError:
                continue
            break

        return confirmation

    @staticmethod
    def confirm_using(code):
        try:
            c = EmailConfirmation.objects.get(code=code)
        except EmailConfirmation.DoesNotExist:
            c = None
        if c:
            if not c.is_confirmed:
                c.is_confirmed = True
                c.confirmed_at = datetime.now()
                c.save()
                return (c.student, False)
            else:
                return (c.student, True)
        else:
            return (None, False)

    def get_confirmation_url(self):
        #return 'http://localhost:8000/std/confirm_email/%s' % self.code
        return 'http://wt.eng.ku.ac.th/wt/std/confirm_email/%s/' % self.code


class SelectionRound(models.Model):
    number = models.IntegerField(verbose_name=u"รอบ")
    beginning_time = models.DateTimeField(verbose_name=u'วันและเวลาที่เปิดให้นิสิตเลือก')
    end_time = models.DateTimeField(verbose_name=u'วันและเวลาสิ้นสุดการเลือก')

    year = models.IntegerField(verbose_name=u'ปีการศึกษา')

    departments = models.ManyToManyField(Department)
    
    class Meta:
        ordering = ['-year','number']
    
    def __unicode__(self):
        return "Round %d of %d (%s - %s)" % (self.number, self.year, self.beginning_time, self.end_time)

    @staticmethod
    def get_round(number, year=None):
        if year == None:
            year = get_next_worktraining_year()
        try:
            r = SelectionRound.objects.get(number=number,year=year)
        except SelectionRound.DoesNotExist:
            return None
        return r

    @staticmethod
    def get_all_rounds(year=None):
        if year == None:
            year = get_next_worktraining_year()
        return SelectionRound.objects.filter(year=year)
    

class DepartmentAdditionalSelectionRound(models.Model):
    year = models.IntegerField(verbose_name=u'ปีการศึกษา')
    number = models.IntegerField(verbose_name=u'รอบที่เห็น')
    beginning_time = models.DateTimeField(verbose_name=u'วันและเวลาที่เปิดให้นิสิตเลือก')
    end_time = models.DateTimeField(verbose_name=u'วันและเวลาสิ้นสุดการเลือก')
    department = models.ForeignKey(Department)
    
    def __unicode__(self):
        return u"Round %d of %d (%s - %s) (%s)" % (self.number, self.year, self.beginning_time, self.end_time, self.department)

    @staticmethod
    def get_for_department(year, department, now=None):
        rounds = (DepartmentAdditionalSelectionRound.
                  objects.
                  filter(year=year,
                         department=department).
                  all())

        if now:
            t = now
        else:
            t = datetime.now()
        for r in rounds:
            if (r.beginning_time <= t) and (t <= r.end_time):
                return r
        return None
            
    @staticmethod
    def get_for_department_as_selection_round(year, department):
        r = DepartmentAdditionalSelectionRound.get_for_department(year, 
                                                                  department)
        if r:
            fake_round = SelectionRound()
            fake_round.number = r.number
            fake_round.beginning_time = r.beginning_time
            fake_round.end_time = r.end_time
            fake_round.year = r.year
            return fake_round
        else:
            return None


class StudentSelection(models.Model):
    student = models.ForeignKey(Student,
                                related_name='selections')
    company = models.ForeignKey(Company,
                                related_name='student_selections')
    receipt = models.ForeignKey(Receipt,
                                related_name='student_selections',
                                null=True,
                                blank=True,
                                default=None)
    round_number = models.IntegerField(verbose_name=u'หมายเลขรอบ')
    year = models.IntegerField(verbose_name=u'ปีการศึกษา')
    selection_at = models.DateTimeField(verbose_name=u'เวลาที่นิสิตเลือก')
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=u'เวลาที่นิสิตเลือกเป็นครั้งแรก')
    modified_at = models.DateTimeField(auto_now=True,
                                       verbose_name=u'เวลาแก้ไขล่าสุด')
    result = models.NullBooleanField(null=True,
                                     verbose_name=u'ผลการคัดเลือก')
    verification_token = models.CharField(max_length=20,
                                          blank=True,
                                          default='')

    extra_ranking = models.IntegerField(default=0,
                                        verbose_name=u'สำหรับจัดเรียงกรณีที่เวลาตรงกัน')

    is_imported = models.BooleanField(default=False,
                                      verbose_name=u'เป็นการเลือกที่ถูกนำเข้าจากเฟสบุ๊ค')

    class Meta:
        ordering = ['selection_at', 'extra_ranking']

    def __unicode__(self):
        return self.student.full_name()
    
    def get_token(self):
        if self.verification_token=='':
            return ''

        from django.utils.hashcompat import sha_constructor
        hash = sha_constructor("%d-%d-%d-%d-%s" %
                               (self.year,
                                self.round_number,
                                self.student.id,
                                self.company.id,
                                self.verification_token)).hexdigest()[:20]
        return hash


    def save(self, *args, **kwargs):
        self.verification_token = ''.join([str(random.random())[-4:] for i in range(4)])
        super(StudentSelection, self).save(*args, **kwargs) 


    def save_to_assignment(self):
        if not self.result:
            return

        student = self.student
        current_assignment = student.assignment_for_year(self.year)
        if not current_assignment:
            current_assignment = Assignment(year=self.year,

std/templates/std/agreement.html
{% extends "std/base.html" %}

{% block title %}ข้อตกลงการฝึกงาน{% endblock %}
{% load wt_media %}

{% block content %}
<h1>สมัครเข้าฝึกงานหรือสหกิจศึกษา: {{ student.full_name }}</h1>
{% if not credit_validation %}
  <div class="form-section">
    ตามระเบียบแล้วนิสิตจะต้องมีหน่วยกิตสะสมอย่างน้อย 60 หน่วยจึงจะสามารถสมัครฝึกงานได้ &nbsp; เนื่องจากระบบยังไม่มีข้อมูลดังกล่าว ระบบจึงอนุญาตให้นิสิตสมัครฝึกงานก่อน แต่ถ้าภายหลังพบว่านิสิตมีหน่วยกิตไม่ครบ การสมัครในครั้งนี้จะถูกยกเลิกไปโดยอัตโนมัติ
  </div>
{% endif %}
<p>
  กรุณาอ่านระเบียบและขั้นตอนเกี่ยวกับการฝึกงานและสหกิจศึกษาด้านล่างนี้ และกดตกลงตามเงื่อนไขในตอนท้ายหน้านี้เพื่อสมัครเข้าฝึกงานหรือสหกิจศึกษา<br>
  <span style="color:red; font-size:120%"><b>ถ้านิสิตยังไม่กดตกลงเงื่อนไข จะถือว่าการสมัครยังไม่สมบูรณ์</b></span><br>
  <b>เมื่อตกลงเงื่อนไขแล้วจะถือว่าการสมัครสมบูรณ์</b> นิสิตจะสามารถเลือกว่าจะฝึกงานหรือฝึกสหกิจศึกษาได้ในหน้าถัดไป
</p>
<div class="form-section">
  {% include "std/include/agreement_text.html" %}
</div>
<p>
  <form action="{% url 'std_checkstatus' %}" method="POST">
    <input class="button red" type="submit" name="cancel" value="ไม่ตกลงตามเงื่อนไข"/>
    <input id="accept_type0_button_id" class="button blue" type="submit" name="accept_type0" value="ข้าพเจ้าอ่านและตกลงตามเงื่อนไขข้างต้นและสมัครฝึกงานหรือสหกิจศึกษา"/>
    <input style="display: none;" id="accept_type1_button_id" class="button blue" type="submit" name="accept_type1" value="ข้าพเจ้าอ่านและตกลงตามเงื่อนไขข้างต้นและขอสมัครฝึกงาน"/>
    <input style="display: none;" id="accept_type2_button_id" class="button blue" type="submit" name="accept_type2" value="ข้าพเจ้าอ่านและตกลงตามเงื่อนไขข้างต้นและขอสมัครแบบที่ 2"/>
    <input style="display: none;" id="accept_type3_button_id" class="button blue" type="submit" name="accept_type3" value="ข้าพเจ้าอ่านและตกลงตามเงื่อนไขข้างต้นและขอสมัครฝึกสหกิจศึกษา"/>
  </form>
</p>
<p style="color: #303030;">
  <small>
    <b>หมายเหตุ:</b> นิสิตสามารถสอบถามรายละเอียด และติดตามข่าวสารการฝึกงานได้ที่
    <a href="https://www.facebook.com/internship.eng.ku" target="_blank">facebook page</a>
  </small>
</p>
<script>
 $(function(){
   $("#accept_type1_button_id").click(function(){
     return confirm("คุณได้อ่านข้อตกลงและแน่ใจที่จะสมัครฝึกงาน โดยจัดหาหน่วยงานเอง หรือไม่\nถ้าแน่ใจกด OK หรือ ตกลง");
   });
   $("#accept_type2_button_id").click(function(){
     return confirm("คุณได้อ่านข้อตกลงและแน่ใจที่จะสมัครในแบบที่ 2 (ให้คณะจัดหาหน่วยงานให้) หรือไม่\nถ้าแน่ใจกด OK หรือ ตกลง");
   });
   $("#accept_type3_button_id").click(function(){
     return confirm("คุณได้อ่านข้อตกลงและแน่ใจที่จะสมัครโครงการสหกิจศึกษาหรือไม่\nถ้าแน่ใจกด OK หรือ ตกลง");
   });
 });
</script>
{% endblock content %}

std/templates/std/appl_condition_failed.html
{% extends "std/base.html" %}

{% load wt_media %}

{% block content %}
<h1>ขออภัย {{ student.full_name }}</h1>
<p class="error_message">
  จากข้อมูลในระบบที่เรามี จำนวนหน่วยกิตของคุณไม่เพียงพอต่อการฝึกงาน
</p>
<p>
  จำนวนหน่วยกิตที่ต้องการคือ {{required_credits}} 
  {% if current_credits %}
    แต่หน่วยกิตสะสมปัจจุบันคือ <font color=red>{{ current_credits }}</font>
  {% else %}
    แต่ขณะนี้ในระบบไม่มีข้อมูลหน่วยกิตของคุณ
  {% endif %}
</p>
{% comment %}
<p>
  ทั้งนี้อาจมีสาเหตุมาจากข้อมูลหน่วยกิตของเรายังไม่ตรงกับข้อมูลจริงในวันนี้ ทางทีมงานจะทยอยปรับปรุงข้อมูลให้ตรงกับความเป็นจริงให้เรียบร้อยเร็ว ๆ นี้
</p>
{% endcomment %}
<p>
  อย่างไรก็ตาม ถ้าตามข้อมูลจริงแล้ว หน่วยกิตของคุณถึงเกณฑ์ที่กำหนด คือ {{ required_credits }} หน่วย คุณสามารถสมัครเข้าฝึกงานได้ ผ่านทางกรรมการกิจการนิสิตประจำภาควิชา โดยนำใบทรานสคริปต์ไปยื่นเป็นหลักฐานกับกรรมการกิจการนิสิตประจำภาควิชา เพื่อให้กรรมการดำเนินการสมัครฝึกงานให้กับคุณ
<br/>
</p>
{% endblock content %}

std/templates/std/appl_deadline.html
{% extends "std/base.html" %}

{% load wt_media %}

{% block content %}
<h1>ขออภัย {{ student.full_name }}</h1>
<p class="error_message">
  หมดเขตการขอเข้าฝึกงานในภาคการศึกษาหน้าแล้ว
</p>
<p>
  อย่างไรก็ตาม
ถ้าคุณคิดว่าคุณได้สมัครในเวลาหรือมีเหตุผลจำเป็นหรือมีปัญหาเกี่ยวกับด้านเทคนิค
คุณสามารถติดต่อหน่วยกิจการนิสิตเพื่อสอบถามได้
</p>
{% endblock content %}

std/templates/std/base.html
{% extends "base.html" %}

{% block title %}ระบบนิสิต{% endblock %}

{% block extra-head %}
  {% include "include/jquery_scripts.html" %}
{% endblock %}

{% block menu %}
{% include "include/navigation_scripts.html" %}
<ul id="nav">
  <li><a href="{% url 'front_page' %}">หน้าหลัก</a></li>
  <li {% if currentpage == 'std' %}class="current"{% endif %}><a href="{% url 'std_index' %}" >ข้อมูลการฝึกงาน</a></li>
  <li {% if currentpage == 'profile' %}class="current"{% endif %}><a href="{% url 'std_profile' %}">ข้อมูลส่วนตัว</a></li>

  {% comment %}
  <li class="subnav-list{% if currentpage == 'company' %} current{% endif %}">
      <a href="#" class="subnav-link" >เลือกสถานประกอบการ</a>
      <ul id="company_subnav">
	<li><a href="{% url 'direct_appl_std_list' %}">สถานประกอบการที่คัดนิสิตเอง</a></li>
      </ul>
    </li>
  {% endcomment %}

  <li><a href="{% url 'std_logout' %}">ออกจากระบบ</a></li>
</ul>
<div id="clear"></div>
{% endblock menu %}

{% block content %}
{% endblock content %}

std/templates/std/company_list.html
{% extends "std/base.html" %}

{% load wt_media %}

{% block content %}
<div style="float:right">
<a class="button red" href="{% url 'std_index' %}">กลับไปหน้าหลักของนิสิต</a>
</div>
<h1>รายการสถานประกอบการที่ตอบจดหมายขอความอนุเคราะห์สำหรับสาขาวิชา{{ department }}</h1>

{% if available_receipts %}
  {% include "std/include/std_selection/available_receipts.html" %}
{% else %}
  ยังไม่มีข้อมูล
{% endif %}
{% endblock content %}

std/templates/std/editprofile.html
{% extends "std/base.html" %}

{% block content %}
<h1>แก้ไขข้อมูลส่วนตัว</h1>
<table>
	<tr>
	    <td>ชื่อ-สกุล</td><td>: {{ student.prefix }}{{ student.first_name }} {{ student.last_name }} </td>
		<td class="darkblue">ในกรณีที่ ชื่อ-สกุล ผิดให้ติดต่อหน่วยกิจการนิสิตโดยตรง</td>
    </tr>
    <tr>
	    <td>รหัสนิสิต</td><td>: {{ student.student_id }}</td>
    </tr>       
	<form action="{% url 'std_edit' %}" method="POST">
    <tr>    
  		<td><label for="id_email">E-mail</label></td><td>: {{ form.email }} {{ form.email.errors }} </td>
    </tr>
    <tr>
        <td><label for="id_tel_no">เบอร์โทรศัพท์</label></td><td>: {{ form.tel_no }} {{ form.tel_no.errors }}</td>
    </tr>
	<tr>
	    <td><label for="id_department">ภาควิชา</label>ภาควิชา</td><td>: {{ form.department }} {{form.department.errors }}</td>
    </tr>
    <tr>
    	<td></td>
        <td>
               <br/><input type="submit" value="แก้ไขข้อมูลส่วนตัว" class="medium green button"/>
        </td>
    </tr>
  	</form>
</table>
{% endblock content %}

std/templates/std/email_confirmed.html
{% extends "std/base.html" %}

{% block content %}
<h1>ยืนยันอีเมล์เรียบร้อย</h1>
<p>
  คุณได้ยืนยันอีเมล์ของ {{ student }} เรียบร้อยแล้ว<br/>
  <a href="{% url 'front_page' %}" class="button green">กลับไปหน้าหลัก</a>
</p>
{% endblock content %}

std/templates/std/index_constructions.html
{% extends "std/base.html" %}

{% load wt_media %}

{% block content %}
<h1>ระบบฝึกงานอยู่ระหว่างการปรับปรุง</h1>

<div class="form-section">
  ระบบฝึกงานส่วนนี้อยู่ระหว่างการปรับปรุง คุณจะสามารถเข้าใช้ได้อีกครั้งภายในวันที่ 27 มิ.ย. 2557 ขออภัยในความไม่สะดวก
</div>
{% endblock content %}