direct_appl/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns(
    'direct_appl.views',

    # regis views
    url(r'^company/list/', 'regis_views.company_list',
        name='direct_appl_regis_company_list'),
    url(r'^company/add/', 'regis_views.company_add',
        name='direct_appl_regis_company_add'),
    url(r'^company/(\d+)/edit/$', 'regis_views.company_edit',
        name='direct_appl_regis_company_edit'),
    url(r'^company/(\d+)/$', 'regis_views.company_show',
        name='direct_appl_regis_company_show'),
    url(r'^company/(\d+)/search/$', 'regis_views.company_student_search',
        name='direct_appl_regis_company_student_search'),
    url(r'^company/apply/(\d+)/(\d+)/', 'regis_views.company_apply',
        name='direct_appl_regis_company_apply'),
    url(r'^company/cancel/(\d+)/(\d+)/', 'regis_views.company_cancel',
        name='direct_appl_regis_company_cancel'),
    url(r'^company/(\d+)/approve/$', 'regis_views.company_approve',
        name='direct_appl_regis_company_approve'),
    url(r'^company/(\d+)/toggle/$', 'regis_views.company_toggle',
        name='direct_appl_regis_company_toggle'),

    # student views
    url(r'^std/companies/', 'std_views.list',
        name='direct_appl_std_list'),
    url(r'^std/company/(\d+)/', 'std_views.show',
        name='direct_appl_std_show'),
    url(r'^std/applications/', 'std_views.show_applications',
        name='direct_appl_std_show_applications'),
)

regis/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns(
    'regis.views',

    url(r'^$', 'index', name='regis_index'),
    url(r'^company/', include('regis.company.urls')),
    url(r'^student/', include('regis.student.urls')),
    url(r'^department/', include('regis.department.urls')),
    url(r'^config/', include('regis.config.urls')),
    url(r'^mail/', include('regis.mass_mailing.urls')),
)

urlpatterns += patterns(
    'regis.stats.views',
    
    url(r'^stats/details/$', 'assignment_details_by_dept' , name='regis_stat_detail'),
    url(r'^stats/$', 'assignment_stats' , name='regis_stat'),
    url(r'^stats/(\d+)/$', 'assignment_stats', name='regis_stat'),
    url(r'^stats/students/(\d+)/(\w+)$', 'show_std_list' , name='regis_show_std_list'),
    url(r'^stats/students/(\d+)/(\w+)/(\d+)/$', 'show_std_list' , name='regis_show_std_list'),

    url(r'^stats/assignments/companies/$', 'assignment_company_stats', name='regis_stats_assignments_companies'),
    url(r'^stats/assignments/companies/(\d+)/$', 'assignment_company_stats', name='regis_stats_assignments_companies'),

    url(r'^stats/coop/$', 'coop_stats_by_dept', name='regis_stats_coop'),
    url(r'^stats/coop/requests/(\d+)/(\d+)/', 'coop_report', name='regis_stats_coop_report'),
)

std/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns(
    'std.views',
    url(r'^$', 'index', name='std_index'),
    url(r'^underconst/$', 'underconst', name='std_under_construction'),

    url(r'^login/$', 'auth.login', name='std_login'),
    url(r'^login/token/$', 'auth.login_with_token', name='std_login_with_token'),
    url(r'^logout/$', 'auth.logout', name='std_logout'),

    url(r'^edit/', 'profile.edit', name='std_edit'),
    url(r'^profile/','profile.profile',name='std_profile'),
    url(r'^confirm_email/(.+)/','profile.confirm_email'),
    url(r'^regtype/(\d)/$','choose_reg_type',name='std_choose_reg_type'),
    url(r'^regtype/(\d)/confirm/','confirm_reg_type',name='std_confirm_reg_type'),

    url(r'^checkstatus/$','check_internship_status',name='std_checkstatus'),
    url(r'^print_request_form/$','PrintRequestForm',name='std_print_request_form'),

    url(r'^companies/$','company_list',name='std_company_list'),
      
    url(r'^selection/$','company_selection.list',name='std_selection_list'),
    url(r'^selection/select/(\d+)/$','company_selection.select',
        name='std_selection_select'),
    url(r'^selection/deselect/(\d+)/$','company_selection.deselect',
        name='std_selection_deselect'),

    url(r'^company/search/$', 'company.search',
        name='std_company_search'),
    url(r'^company/search/(.+)/$','company.list_by_char',name='std_company_list_by_char'),

    url(r'^self_appl/$', 'company.self_appl_index',
        name='std_self_appl_index'),
    url(r'^self_appl/confirm/$', 'company.self_appl_confirm',
        name='std_self_appl_confirm'),

    url(r'^self_appl/requests/$', 'company.new_request',
        name='std_self_appl_new_company_request'),
    url(r'^self_appl/requests/confirm/(\d+)/', 'company.request_confirm',
        name='std_self_appl_request_confirm'),
    url(r'^self_appl/requests/inactive/$', 'company.inactive_requests',
        name='std_self_appl_inactive_company_requests'),
    url(r'^self_appl/requests/print/(\d+)/$', 'company.print_request',
        name='std_self_appl_request_print'),
    url(r'^self_appl/requests/sending_letter/(\d+)/$', 'company.print_request_sending_letter_pdf',
        name='std_self_appl_print_request_sending_letter'),

    url(r'^self_appl/announcement/print/$', 'company.print_announcement',
        name='std_self_appl_request_print_announcement'),

    url(r'^self_appl/stdsearch/$', 'company.student_search',
        name='std_self_appl_student_search'),
    url(r'^self_appl/name/search/$', 'company.search_by_name_ajax',
        name='std_self_appl_company_search_by_name_ajax'),

    url(r'^self_appl/applications/create/$', 'company.create_direct_application',
        name='std_self_appl_create_application'),
    url(r'^self_appl/applications/update/(\d+)/$', 'company.update_direct_application',
        name='std_self_appl_update_application'),
    url(r'^self_appl/applications/cancel/(\d+)/$', 'company.cancel_direct_application',
        name='std_self_appl_cancel_application'),
    url(r'^self_appl/applications/print/(\d+)/$', 'company.print_direct_application_letter',
        name='std_self_appl_print_application_letter'),
    url(r'^self_appl/applications/verified/$', 'company.list_verified_direct_application_companies',
        name='std_self_appl_list_verified_companies'),
    url(r'^self_appl/applications/sending_letter/(\d+)/$', 'company.print_direct_application_sending_letter_pdf',
        name='std_self_appl_print_application_sending_letter'),
    
    url(r'^print_company_letter/(\d+)/$',
        'print_letter', name='std_print_letter'),

    url(r'^coop/$', 'coop.index',
        name='std_coop_index'),
    url(r'^coop/address/$', 'coop.update_address',
        name='std_coop_address'),

    url(r'^coop/companies/$', 'coop.update_company',
        name='std_coop_create_company'),

    url(r'^coop/companies/(?P<co_op_company_id>\d+)/$', 'coop.update_company',
        name='std_coop_update_company'),
    url(r'^coop/requests/(?P<co_op_company_id>\d+)/$', 'coop.create_request',
        name='std_coop_create_request'),

    url(r'^coop/requests/print/(\d+)/([a-z]+)/$', 'coop.print_request',
        name='std_coop_request_print'),
)

worktraining/urls.py
from django.conf.urls import url, include, patterns
from django.conf import settings

import django.contrib.staticfiles.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import commons.views
import regis.announcement.views
import evaluations.views
import commons.auth_views

urlpatterns = patterns(
    '',
    #(r'^$',
    # 'django.views.generic.simple.direct_to_template',
    # {'template': 'front.html'}),
    url(r'^$', commons.views.index, name='front_page'),

    url(r'^announcement/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_detail,
        name='front_announcement_detail'),
    url(r'^announcement/edit/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_edit,
        name='announcement_edit'),
    url(r'^announcement/index/$',
        regis.announcement.views.list,
        name='announcement_index'),
    url(r'^announcement/create/$',
        regis.announcement.views.announcement_create,
        name='announcement_create'),
    url(r'^announcement/delete/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_delete,
        name='announcement_delete'),
    
    (r'^regis/', include('regis.urls')),
    (r'^std/', include('std.urls')),
    (r'^eval/', include('evaluations.urls')),
    (r'^committee/', include('committee.urls')),
    (r'^commons/', include('commons.urls')),
    (r'^direct/', include('direct_appl.urls')),

    url(r'^ev/(\d+)/(.+)/$',
        evaluations.views.edit_by_company,
        name='short_evaluations_edit_by_company'),


    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # authentication
    url(r'^accounts/login/$', 
        commons.auth_views.login,
        name='admin_login'),
    url(r'^accounts/logout/$', 
        'django.contrib.auth.views.logout',
        { 'next_page': settings.LOGOUT_URL },
        name='admin_logout'),
    url(r'^accounts/login/token/$',
        commons.auth_views.login_user_with_token,
        name='admin_login_token'),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        # Static media (for development)
        (r'^site_media/(?P<path>.*)$',
         django.contrib.staticfiles.views.serve),
    )

direct_appl/models.py
# -*- coding: utf-8 -*-

from django.db import models

from regis.models import Company, Student

DIRECT_APPL_ONLY_CHOICES = (
    (True,u'คัดเลือกเองอย่างเดียว'),
    (False,u'ให้คณะคัดเลือกให้บางส่วนด้วย'))

class DirectApplicationPosition(models.Model):
    company = models.ForeignKey(Company, 
                                verbose_name=u'สถานประกอบการ',
                                related_name='direct_appl_info_set')
    year = models.IntegerField(
        verbose_name=u'ปีที่เข้ารับฝึกงาน')

    is_direct_appl_only = models.BooleanField(
        default=True,
        verbose_name=u'คัดเลือกเองเท่านั้น?',
        help_text=u'สถานประกอบการรับเฉพาะที่คัดเลือกเองเท่านั้นหรือไม่',
        choices=DIRECT_APPL_ONLY_CHOICES)

    appl_requirements = models.TextField(
        blank=True,
        verbose_name=u'เงื่อนไขในการสมัคร')

    application_deadline = models.DateField(null=True,
                                            default=None,
                                            blank=True,
                                            verbose_name=u'ส่งใบสมัครภายในวันที่')

    application_form_file = models.FileField( 
        upload_to='applications/%y/',
        null=True,
        default=None,
        blank=True,
        verbose_name=u'ใบสมัคร')

    is_hidden = models.BooleanField(default=False,
                                    verbose_name=u'ซ่อน')

    class Meta:
        verbose_name = u'ตำแหน่งงานที่สถานประกอบการคัดเลือกเอง'
        verbose_name_plural = verbose_name

    @staticmethod
    def get_all_for_year(year):
        return (DirectApplicationPosition
                .objects
                .select_related('company')
                .filter(year=year))

APPLICATION_RESULT_CHOICES = (
    (None,u'รอผล'),
    (True,u'สถานประกอบการตอบรับ'),
    (False,u'สถานประกอบการตอบปฏิเสธ'))

class StudentApplication(models.Model):
    student = models.ForeignKey(Student,
                                verbose_name=u'นิสิต')
    position = models.ForeignKey(DirectApplicationPosition,
                                 verbose_name=u'ตำแหน่งงาน')
    is_accepted = models.NullBooleanField(default=None,
                                          choices=APPLICATION_RESULT_CHOICES,
                                          verbose_name=u'ผลการสมัคร')

    apply_at = models.DateTimeField(auto_now_add=True,
                                    verbose_name=u'วันที่ได้รับใบสมัคร')
    result_date = models.DateField(blank=True,
                                   null=True,
                                   default=None,
                                   verbose_name=u'วันที่ทราบผลการสมัคร')

    class Meta:
        ordering = ['apply_at']


    def is_rejected(self):
        return self.is_accepted == False

    def __unicode__(self):
        return "%s applied for %s in %d" % (self.student.full_name(),
                                            self.position.company.name,
                                            self.position.year)

    @staticmethod
    def all_for_position(position):
        return (StudentApplication
                .objects
                .filter(position=position)
                .all())

    @staticmethod
    def all_for_student(student, year=None,related=True):
        if related:
            results = (StudentApplication
                       .objects
                       .filter(student=student)
                       .select_related('student','position')
                       .all())
        else:
            results = (StudentApplication
                       .objects
                       .filter(student=student)
                       .all())
        if year:
            results = results.filter(position__year__exact=year)
        return results

    @staticmethod
    def count_all_for_student(student, year=None):
        results = (StudentApplication
                   .objects
                   .filter(student=student)
                   .all())
        if year:
            results = results.filter(position__year__exact=year)
        return results.count()

    @staticmethod
    def all_for_department(department, year=None):
        results = (StudentApplication
                   .objects
                   .filter(student__department=department)
                   .select_related('student','position')
                   .all())
        if year:
            results = results.filter(position__year__exact=year)
        return results

direct_appl/views/std_views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext

from direct_appl.models import DirectApplicationPosition, StudentApplication
from regis.models import Student
from std.decorators import std_login_required
from commons.academia import get_next_worktraining_year

@std_login_required
def list(request):
    return redirect('std_index')
    year = get_next_worktraining_year()

    if not request.student.has_registered(year):
        return render_to_response("commons/forbidden.html")

    direct_positions = DirectApplicationPosition.get_all_for_year(year).filter(is_hidden=False)

    return render_to_response("direct_appl/std/list.html",
                              { 'year': year,
                                'direct_positions': direct_positions,
                                'currentpage': 'company' },
                              context_instance=RequestContext(request))

@std_login_required
def show(request, direct_position_id):
    year = get_next_worktraining_year()

    if not request.student.has_registered(year):
        return render_to_response("commons/forbidden.html")

    direct_position = get_object_or_404(DirectApplicationPosition,
                                        pk=direct_position_id)

    company = direct_position.company
    requirements = direct_position.appl_requirements
    return render_to_response("direct_appl/std/show.html",
                              { 'year': year,
                                'company': company,
                                'requirements': requirements,
                                'direct_position': direct_position,
                                'currentpage': 'company' },
                              context_instance=RequestContext(request))


@std_login_required
def show_applications(request):
    student = request.student
    year = get_next_worktraining_year()

    if not request.student.has_registered(year):
        return render_to_response("commons/forbidden.html")

    applications = StudentApplication.all_for_student(student,year)

    return render_to_response("direct_appl/std/show_applications.html",
                              { 'student': student,
                                'year': year,
                                'applications': applications },
                              context_instance=RequestContext(request))

direct_appl/templates/direct_appl/regis/add.html
{% extends "regis/base.html" %}
{% block content %}
<h1>เพิ่มรายชื่อสถานประกอบการที่ขอคัดเลือกนิสิตเข้าฝึกงานเอง ประจำปีการศึกษา {{ year }}</h1>

<form method="post" enctype="multipart/form-data">
  <table class="top-align">
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
	<input type="submit" name="submit" value="เพิ่มข้อมูล">
	<input type="submit" name="cancel" value="ยกเลิก">
      </td>
    </tr>
  </table>
</form>

<script type="text/javascript">
  $(function() {
    $("#id_application_deadline").datepicker({dateFormat: "yy-mm-dd"});
    $("#id_company_name").autocomplete({source: "{% url 'company_search_by_name_ajax' %}"});
  });
</script>
{% endblock %}

direct_appl/templates/direct_appl/regis/approve.html
{% extends "regis/base.html" %}

{% load wt_media %}

{% block content %}
<div style="float: right">
  <a href="{% url 'direct_appl_regis_company_show' direct_position.id %}"
     class="button red small">
    กลับไปหน้าข้อมูล
  </a>
</div>
<h1>บันทึกผลการสมัคร {{ company.name }}</h1>

{% if error_msg %}
<div class="info_message">
เกิดข้อผิดพลาด ไม่สามารถจัดเก็บได้เนื่องจาก:<br/>
{{ error_msg|linebreaksbr }}
</div>
{% endif %}

<form method="post" class="form-section">
  <h3>รายชื่อนิสิตที่สมัคร</h3>
  <table>
    <tr>
      <th>คนที่</th>
      <th>เลขประจำตัว</th>
      <th>ชื่อ-นามสกุล</th>
      <th>สาขาวิชา</th>
      <th colspan="2">ผลการสมัคร</th>
      <th></th>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td width="50px">รับ</td>
      <td width="50px">ไม่รับ</td>
      <td></td>
    </tr>
    {% for application in applications %}
      <tr>
	<td>{{ forloop.counter }}</td>
	<td>{{ application.student.student_id }}</td>
	<td>{{ application.student.full_name }}</td>
	<td>{{ application.student.department }}</td>
	{% if not application.student.assigned_company %}
  	  <td style="background: #f0fff0">
	    <input class="approve_box app_box_{{ application.id }}" 
	  	   id="id_yes_app_{{ application.id }}" 
		   name="yes_app_{{ application.id }}" 
		   type="checkbox"
		   {% if application.is_accepted %}checked{% endif %}
		   />
	  </td>
	  <td style="background: #fff0f0">
	    <input class="approve_box app_box_{{ application.id }}" 
		   id="id_no_app_{{ application.id }}" 
		   name="no_app_{{ application.id }}" 
		   type="checkbox"
		   {% if not application.is_accepted and application.is_accepted != None %}checked{% endif %}
		   />
	  </td>
	  {% if application.outstanding_apps %}
	    <td>
	      <small>[<a href="" class="other_app_link" id="id_other_app_{{ application.id }}_link">ใบสมัครอื่น</a>]</small>
	      <div class="other_app_info" style="display:none">
		{% for o in application.outstanding_apps %}
  		  <b>{{ o.position.company }}</b><br/>
		  {{ o.position.company.contact_name|default_if_none:"" }} 
		  {{ o.position.company.tel_no|default_if_none:"" }} 
		{% endfor %}  
	      </div>
	    </td>
	  {% endif %}
	{% else %}
          <td colspan="3">
	    <small>
	      [ได้รับคัดเลือกแล้ว: {{ application.student.assigned_company }}]
	    </small>
	  </td>
        {% endif %}
      </tr>
    {% empty %}
      <tr> 
	<td colspan="5">ยังไม่มีนิสิตสมัคร</td>
      </tr>
    {% endfor %}
  </table>
  <input id="id_ok_button" name="ok" type="submit" value="จัดเก็บ">
  <input id="id_cancel_button" name="cancel" type="submit" value="ยกเลิก">
</form>  

<script type="text/javascript">
  function get_app_id_from_id(id) {
    i = id.split("_");
    return i[3];
  }

  function clear_opposite_box(id) {
    myid = get_app_id_from_id(id);
    if(id.indexOf("id_yes_app")!=-1)
      $("#id_no_app_" + myid).attr("checked",false);
    else
      $("#id_yes_app_" + myid).attr("checked",false);
  }

  $(function() {
    $("#id_ok_button").click(function() {
      return confirm("ต้องการบันทึกข้อมูลนี้หรือไม่\nถ้าบันทึกแล้วจะมีอีเมล์แจ้งไปที่นิสิตเกี่ยวกับผลนี้\nถ้าแน่ใจกรุณายืนยัน");
    });
    $("#id_cancel_button").click(function() {
      return confirm("ต้องการยกเลิกการบันทึกข้อมูลนี้หรือไม่\nถ้าแน่ใจกรุณายืนยัน");
    });
    $(".approve_box").click(function() {
      clear_opposite_box($(this).attr("id"));
    });
    $(".other_app_link").click(function() {
      $(this).parentsUntil("td").parent().find(".other_app_info").toggle();
      return false;
    });
  });
</script>
{% endblock %}

direct_appl/templates/direct_appl/regis/company_student_search.html
{% extends "regis/base.html" %}

{% load wt_media %}

{% block content %}
<h1>สมัครนิสิตนิสิตเข้าคัดเลือก {{ company.name }} สำหรับการฝึกงานปีการศึกษา {{ year }}</h1>

<form 
   action=""
   method="post"
   class="form-section">
  รหัสนิสิต: {{ form.student_id }}&nbsp;&nbsp;
  ชื่อ: {{ form.student_name }}&nbsp;&nbsp;
  <input type="submit" value="ค้นหานิสิต"/>
</form>

{% if too_many_results %}
  <p>ผลลัพธ์ที่ค้นได้มีมากเกินไป กรุณาใส่ข้อมูลของนิสิตเพิ่มขึ้น</p>
{% else %}
  {% if students != None %}
    <h3>รายชื่อนิสิตที่ตรงกับเงื่อนไข</h3>
    <table>
      <tr>
	<th>เลขประจำตัว</th>
	<th>ชื่อ</th>
	<th>สาขาวิชา</th>
	<th></th>
      </tr>
      {% for student in students %}
        <tr>
	  <td>{{ student.student_id }}</td>
	  <td>{{ student.full_name }}</td>
	  <td>{{ student.department }}</td>
	  <td>
	    {% if student.is_eligible_to_apply_more_direct_application %}
	      <a href="{% url 'direct_appl_regis_company_apply' direct_position.id student.student_id %}"
		 class="button small green">
		สมัครเข้ารับการคัดเลือก
	      </a>
	    {% else %}
	      ไม่สามารถสมัครได้: {{ student.reasons_failed_to_apply_more_direct_application }}
	    {% endif %}
	  </td>
	</tr>
      {% empty %}
        <tr>
	  <td></td>
	  <td>ไม่พบข้อมูลนิสิตที่ค้นหา</td>
	</tr>
      {% endfor %}
    </table>
  {% endif %}
{% endif %}

{% endblock %}

direct_appl/templates/direct_appl/regis/edit.html
{% extends "regis/base.html" %}
{% block content %}
<h1>แก้ไขข้อมูลสถานประกอบการที่ขอคัดเลือกนิสิตเข้าฝึกงานเอง ประจำปีการศึกษา {{ year }}</h1>

<form method="post" enctype="multipart/form-data">
  <table class="top-align">
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
	<input type="submit" name="submit" value="แก้ไข">
	<input type="submit" id="delete_submit_button" name="delete" value="ลบรายการ">
	<input type="submit" name="cancel" value="ยกเลิก">
      </td>
    </tr>
  </table>
</form>

<script type="text/javascript">
  $(function() {
    $("#delete_submit_button").click(function() {
      return confirm("คุณแน่ใจที่จะลบสถานประกอบการนี้ออกจากรายการสถานประกอบการที่ขอคัดเลือกนิสิตเองใช้หรือไม่");
    });
    $("#id_application_deadline").datepicker({dateFormat: "yy-mm-dd"});
    $("#id_company_name").autocomplete({source: "{% url 'company_search_by_name_ajax' %}"});
  });
</script>
{% endblock %}

direct_appl/templates/direct_appl/regis/show.html
{% extends "regis/base.html" %}

{% load wt_media %}

{% block content %}
<div style="float: right">
  <a href="{% url 'direct_appl_regis_company_edit' direct_position.id %}"
     class="button blue small">
    แก้ไขข้อมูลการคัดเลือก
  </a>
  <a href="{% url 'direct_appl_regis_company_list' %}"
     class="button red small">
    กลับไปหน้ารายการ
  </a>
</div>
{% include "direct_appl/include/position.html" %}

<div class="form-section">
  <div style="float:right">
    <a href="{% url 'direct_appl_regis_company_student_search' direct_position.id %}"
       class="button blue small">
      สมัครนิสิตเข้าฝึกงานสถานประกอบการนี้
    </a>
    <a href="{% url 'direct_appl_regis_company_approve' direct_position.id %}"
       class="button green small">
      บันทึกผลการสมัคร
    </a>
    <a class="blue button small" href="{% url 'regis_company_print_letter_pdf' direct_position.company.id year  %}">พิมพ์ใบส่งตัว
    </a>
    <a href="{% url 'regis_company_save_label' direct_position.company.id %}" class="button orange small save_label_link">จำที่อยู่</a>
  </div>
  <h3>รายชื่อนิสิตที่สมัคร</h3>

  {% if notice %}
    <div class="notice">
      <span class="notice-text">{{ notice }}</span>
    </div>
  {% endif %}

  <div id="email_list_id" style="display:none; border: 1px solid red; padding: 5px; background: #fff0f0;">
    อีเมล์ของนิสิตทั้งหมด:<br/>
    {% for a in applications %}{{ a.student.email }}, {% endfor %}
  </div>

  <table>
    <tr>
      <th>คนที่</th>
      <th>เลขประจำตัว</th>
      <th>ชื่อ-นามสกุล</th>
      <th>สาขาวิชา</th>
      <th>E-mail (<a href="" id="email_copy_id">คัดลอก</a>)</th>
      <th>ผลการสมัคร</th>
      <th></th>
    </tr>
    {% for application in applications %}
      <tr>
	<td>{{ forloop.counter }}</td>
	<td>{{ application.student.student_id }}</td>
	<td>{{ application.student.full_name }}</td>
	<td>{{ application.student.department }}</td>
	<td><small>{{ application.student.email }}</small></td>
	{% if not application.student.assigned_company %}
	  <td>
	    {{ application.get_is_accepted_display }}
	  </td>
	  <td>
	    <a href="{% url 'direct_appl_regis_company_cancel' direct_position.id application.id %}" class="button red small cancel-button">ยกเลิกการสมัคร</a>
	  </td>
	{% else %}
	  <td colspan="2">
	    <small>
	      [ได้รับคัดเลือกแล้ว: {{ application.student.assigned_company }}]
	    </small>
	  </td>
	{% endif %}
      </tr>
    {% empty %}
      <tr> 
	<td colspan="5">ยังไม่มีนิสิตสมัคร</td>
      </tr>
    {% endfor %}
  </table>
</div>  

<script type="text/javascript">
  $(function() {
    $("#id_application_requirements").hide();
    $(".cancel-button").click(function() {
      return confirm("คุณแน่ใจที่จะยกเลิกการสมัครหรือไม่\nถ้าแน่ใจกรุณายืนยัน");
    });

    $("#email_copy_id").click(function() {
      $("#email_list_id").toggle();
      return false;
    });

    $(".save_label_link").click(function() {
      $url = $(this).attr("href");
      $.get($url, function(data) {
        alert('จำที่อยู่แล้วรวม ' + data + ' สถานประกอบการ');
      });
      return false;
    });
  });
</script>
{% endblock %}