std/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns(
    'std.views',
    url(r'^$', 'index', name='std_index'),
    url(r'^underconst/$', 'underconst', name='std_under_construction'),

    url(r'^login/$', 'auth.login', name='std_login'),
    url(r'^login/token/$', 'auth.login_with_token', name='std_login_with_token'),
    url(r'^logout/$', 'auth.logout', name='std_logout'),

    url(r'^edit/', 'profile.edit', name='std_edit'),
    url(r'^profile/','profile.profile',name='std_profile'),
    url(r'^confirm_email/(.+)/','profile.confirm_email'),
    url(r'^regtype/(\d)/$','choose_reg_type',name='std_choose_reg_type'),
    url(r'^regtype/(\d)/confirm/','confirm_reg_type',name='std_confirm_reg_type'),

    url(r'^checkstatus/$','check_internship_status',name='std_checkstatus'),
    url(r'^print_request_form/$','PrintRequestForm',name='std_print_request_form'),

    url(r'^companies/$','company_list',name='std_company_list'),
      
    url(r'^selection/$','company_selection.list',name='std_selection_list'),
    url(r'^selection/select/(\d+)/$','company_selection.select',
        name='std_selection_select'),
    url(r'^selection/deselect/(\d+)/$','company_selection.deselect',
        name='std_selection_deselect'),

    url(r'^company/search/$', 'company.search',
        name='std_company_search'),
    url(r'^company/search/(.+)/$','company.list_by_char',name='std_company_list_by_char'),

    url(r'^self_appl/$', 'company.self_appl_index',
        name='std_self_appl_index'),
    url(r'^self_appl/confirm/$', 'company.self_appl_confirm',
        name='std_self_appl_confirm'),

    url(r'^self_appl/requests/$', 'company.new_request',
        name='std_self_appl_new_company_request'),
    url(r'^self_appl/requests/confirm/(\d+)/', 'company.request_confirm',
        name='std_self_appl_request_confirm'),
    url(r'^self_appl/requests/inactive/$', 'company.inactive_requests',
        name='std_self_appl_inactive_company_requests'),
    url(r'^self_appl/requests/print/(\d+)/$', 'company.print_request',
        name='std_self_appl_request_print'),
    url(r'^self_appl/requests/sending_letter/(\d+)/$', 'company.print_request_sending_letter_pdf',
        name='std_self_appl_print_request_sending_letter'),

    url(r'^self_appl/announcement/print/$', 'company.print_announcement',
        name='std_self_appl_request_print_announcement'),

    url(r'^self_appl/stdsearch/$', 'company.student_search',
        name='std_self_appl_student_search'),
    url(r'^self_appl/name/search/$', 'company.search_by_name_ajax',
        name='std_self_appl_company_search_by_name_ajax'),

    url(r'^self_appl/applications/create/$', 'company.create_direct_application',
        name='std_self_appl_create_application'),
    url(r'^self_appl/applications/update/(\d+)/$', 'company.update_direct_application',
        name='std_self_appl_update_application'),
    url(r'^self_appl/applications/cancel/(\d+)/$', 'company.cancel_direct_application',
        name='std_self_appl_cancel_application'),
    url(r'^self_appl/applications/print/(\d+)/$', 'company.print_direct_application_letter',
        name='std_self_appl_print_application_letter'),
    url(r'^self_appl/applications/verified/$', 'company.list_verified_direct_application_companies',
        name='std_self_appl_list_verified_companies'),
    url(r'^self_appl/applications/sending_letter/(\d+)/$', 'company.print_direct_application_sending_letter_pdf',
        name='std_self_appl_print_application_sending_letter'),
    
    url(r'^print_company_letter/(\d+)/$',
        'print_letter', name='std_print_letter'),

    url(r'^coop/$', 'coop.index',
        name='std_coop_index'),
    url(r'^coop/address/$', 'coop.update_address',
        name='std_coop_address'),

    url(r'^coop/companies/$', 'coop.update_company',
        name='std_coop_create_company'),

    url(r'^coop/companies/(?P<co_op_company_id>\d+)/$', 'coop.update_company',
        name='std_coop_update_company'),
    url(r'^coop/requests/(?P<co_op_company_id>\d+)/$', 'coop.create_request',
        name='std_coop_create_request'),

    url(r'^coop/requests/print/(\d+)/([a-z]+)/$', 'coop.print_request',
        name='std_coop_request_print'),
)

worktraining/urls.py
from django.conf.urls import url, include, patterns
from django.conf import settings

import django.contrib.staticfiles.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import commons.views
import regis.announcement.views
import evaluations.views
import commons.auth_views

urlpatterns = patterns(
    '',
    #(r'^$',
    # 'django.views.generic.simple.direct_to_template',
    # {'template': 'front.html'}),
    url(r'^$', commons.views.index, name='front_page'),

    url(r'^announcement/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_detail,
        name='front_announcement_detail'),
    url(r'^announcement/edit/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_edit,
        name='announcement_edit'),
    url(r'^announcement/index/$',
        regis.announcement.views.list,
        name='announcement_index'),
    url(r'^announcement/create/$',
        regis.announcement.views.announcement_create,
        name='announcement_create'),
    url(r'^announcement/delete/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_delete,
        name='announcement_delete'),
    
    (r'^regis/', include('regis.urls')),
    (r'^std/', include('std.urls')),
    (r'^eval/', include('evaluations.urls')),
    (r'^committee/', include('committee.urls')),
    (r'^commons/', include('commons.urls')),
    (r'^direct/', include('direct_appl.urls')),

    url(r'^ev/(\d+)/(.+)/$',
        evaluations.views.edit_by_company,
        name='short_evaluations_edit_by_company'),


    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # authentication
    url(r'^accounts/login/$', 
        commons.auth_views.login,
        name='admin_login'),
    url(r'^accounts/logout/$', 
        'django.contrib.auth.views.logout',
        { 'next_page': settings.LOGOUT_URL },
        name='admin_logout'),
    url(r'^accounts/login/token/$',
        commons.auth_views.login_user_with_token,
        name='admin_login_token'),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        # Static media (for development)
        (r'^site_media/(?P<path>.*)$',
         django.contrib.staticfiles.views.serve),
    )

std/views/company.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseForbidden
from django import forms

from datetime import datetime

from commons.models import Configuration
from regis.models import Company, Student, Status
from std.decorators import std_login_required
from std.models import CompanyRequest, RequestStudent, CompanyDirectApplication, VerifiedDirectApplicationCompany, CompanyDirectApplicationDetail, Department
from commons.utils import to_thai_date
from commons.academia import get_current_academic_year, get_next_worktraining_year, can_convert_student_reg_type
from commons.utils import now_within_config_deadline, check_if_can_print_letter
from commons.models import Log
from commons.email import send_regtype_conversion_decision

from reports import build_student_request_letter_pdf_response,  build_sending_letter_pdf_response
from committee.models import CompanyDirectApplicationConfigLetter, CompanyRequestConfigLetter

from evaluations.models import EvaluationSecret

from django.conf import settings

currentpage = 'std'

def search(request):
    companies = []
    if (request.method == 'POST') and ('company_name' in request.POST):
        company_name = request.POST['company_name']
        is_show_instruction = False
    else:
        if 'company_name' in request.GET:
            company_name = request.GET['company_name']
        else:
            company_name = ''
            companies = []
            is_show_instruction = True

    if company_name != '':
        companies = (Company
                     .objects
                     .filter(name__icontains=company_name)
                     .all()[:50])

        if request.method == 'GET':   # ajax
            return render_to_response('std/company/include/company_list.html',
                                      { 'companies': companies })

    return render_to_response('std/company/search.html', 
                              { 'companies': companies,
                                'is_show_instruction': is_show_instruction },
                              context_instance=RequestContext(request))   


def list_by_char(request,ch):
    from commons.academia import STARTING_CHARACTERS

    companies = Company.objects.filter(starting_char=ch).order_by('name').all()
    return render_to_response('std/company/search_by_char.html', 
                              { 'starting_char': ch,
                                'characters': STARTING_CHARACTERS,
                                'companies': companies },
                              context_instance=RequestContext(request))   

class CompanyApplicationForm(forms.Form):
    company_name = forms.CharField(max_length=100,
                                   label=u'ชื่อหน่วยงาน')

class CompanyDirectApplicationDetailForm(forms.ModelForm):
    letter_address = forms.CharField(label=u'ที่อยู่สำหรับส่งหนังสือ',
                                     required=True,
                                     widget=forms.Textarea(attrs={'rows':'3'}))
    period_choice = forms.ChoiceField(choices = [('standard',u'ตามที่คณะกำหนด'),
                                                 ('custom',u'ระบุระยะเวลาเอง')])
    beginning_date = forms.DateField(label=u'วันที่เริ่มฝึกงาน', 
                                     required=False)
    end_date = forms.DateField(label=u'วันที่สิ้นสุดการฝึกงาน',
                               required=False,
                               widget=forms.HiddenInput)

    class Meta:
        model = CompanyDirectApplicationDetail
        exclude = ('application','student','company','created_at',
                   'working_address', 'work_tel_no', 'work_fax_no',
                   'is_default_schedule')

    def clean(self):
        cleaned_data = super(CompanyDirectApplicationDetailForm, self).clean()

        contact_tel_no = cleaned_data.get('contact_tel_no')
        contact_email = cleaned_data.get('contact_email')

        if (not contact_tel_no) and (not contact_email):
            self._errors['contact_tel_no'] = self.error_class([u'ต้องระบุอย่างน้อยเบอร์ติดต่อหรืออีเมล์'])
            del cleaned_data['contact_tel_no']
            if 'contact_email' in cleaned_data:
                self._errors['contact_email'] = self.error_class([u'ต้องระบุอย่างน้อยเบอร์ติดต่อหรืออีเมล์'])
                del cleaned_data['contact_email']

        pchoice = cleaned_data.get('period_choice')
        beginning_date = cleaned_data.get('beginning_date')
        end_date =cleaned_data.get('end_date')

        if pchoice:
            if pchoice == 'custom':
                if not beginning_date or not end_date:
                    self._errors['period_choice'] = self.error_class([u'ระบุวันที่เริ่มและวันที่สิ้นสุดการฝึกงานไม่ถูกต้อง'])
                    del cleaned_data['period_choice']

        return cleaned_data


class CompanyRequestForm(forms.Form):
    company_name = forms.CharField(max_length=100,
                                   label=u'ชื่อหน่วยงาน')
    division_name = forms.CharField(max_length=100,
                                    required=False,
                                    label=u'หน่วยงานย่อย/แผนก/ฝ่าย',
                                    help_text=u'ถ้าไม่มีหน่วยงานย่อย ไม่จำเป็นต้องระบุ')
    letter_address = forms.CharField(label=u'ที่อยู่สำหรับส่งหนังสือ',
                                     required=True,
                                     widget=forms.Textarea(attrs={'rows':'2'}))

    signer_name = forms.CharField(max_length=100,
                                  label=u'ชื่อผู้ที่จะทำจดหมายไปถึง',
                                  required=True)

    contact_person = forms.CharField(max_length=100,
                                     label=u'ผู้ประสานงานการฝึกงาน',
                                     help_text=u'โปรดระบุชื่อผู้ประสานงานการฝึกงานของหน่วยงาน')
    contact_number = forms.CharField(max_length=30,
                                     label=u'เบอร์โทรศัพท์ติดต่อผู้ประสานงาน')
    contact_email = forms.EmailField(label=u'อีเมล์ของผู้ประสานงาน',
                                     required=False)

    working_address = forms.CharField(label=u'สถานที่ตั้ง (ที่นิสิตต้องไปฝึกงาน)',
                                      widget=forms.Textarea(attrs={'rows':'3'}))
    working_number = forms.CharField(max_length=30,
                                     label=u'เบอร์โทรศัพท์')
    working_fax_number = forms.CharField(max_length=30,
                                         label=u'เบอร์โทรสาร')
    description = forms.CharField(widget=forms.Textarea(attrs={'rows':'3'}),
                                  label=u'ลักษณะงานที่มอบหมายให้นิสิตทำ')
    period_choice = forms.ChoiceField(choices = [('standard',u'ตามที่คณะกำหนด'),
                                                 ('custom',u'ระบุระยะเวลาเอง')])

    beginning_date = forms.DateField(label=u'วันที่เริ่มฝึกงาน', 
                                     required=False)
    end_date = forms.DateField(label=u'วันที่สิ้นสุดการฝึกงาน',
                               required=False)

    def clean(self):
        cleaned_data = super(CompanyRequestForm, self).clean()

        pchoice = cleaned_data.get('period_choice')
        beginning_date = cleaned_data.get('beginning_date')
        end_date =cleaned_data.get('end_date')

        if pchoice:
            if pchoice == 'custom':
                if not beginning_date or not end_date:
                    self._errors['period_choice'] = self.error_class([u'ระบุวันที่เริ่มและวันที่สิ้นสุดการฝึกงานไม่ถูกต้อง'])
                    del cleaned_data['period_choice']

        return cleaned_data

    model_fields = ['company_name',
                    'division_name',
                    'letter_address',
                    'signer_name',
                    'contact_person',
                    ('contact_number', 'contact_tel_no'),
                    'contact_email',
                    'working_address',
                    ('working_number','work_tel_no'),
                    ('working_fax_number','work_fax_no'),
                    'description',]

    def save_to_company_request(self, cr):
        for fname in CompanyRequestForm.model_fields:
            if type(fname) != tuple:
                setattr(cr, fname, self.cleaned_data[fname])
            else:
                form_field, obj_field = fname
                setattr(cr, obj_field, self.cleaned_data[form_field])

        if self.cleaned_data['period_choice']=='standard':
            cr.is_default_schedule = True
            cr.beginning_date = None
            cr.end_date = None
        else:
            cr.is_default_schedule = False
            cr.beginning_date = self.cleaned_data['beginning_date']
            cr.end_date = self.cleaned_data['end_date']
        return cr
    
    def new_company_request(self):
        cr = CompanyRequest()
        self.save_to_company_request(cr)

        return cr

    @staticmethod
    def create_from_company_request(company_request):
        initial = {}

        for fname in CompanyRequestForm.model_fields:
            if type(fname) != tuple:
                initial[fname] = getattr(company_request, fname)
            else:
                form_field, obj_field = fname
                initial[form_field] = getattr(company_request, obj_field)

        if company_request.is_default_schedule:
            initial['period_choice'] = 'standard'
        else:
            initial['period_choice'] = 'custom'
            initial['beginning_date'] = company_request.beginning_date
            initial['end_date'] = company_request.end_date
                
        return CompanyRequestForm(initial=initial)
        
    
def confirmed_student_required():
    return not now_within_config_deadline('deadline.free_self_appl_date')

@std_login_required
def student_search(request):
    import re

    DEPARTMENT_MERGE = {6:11, 11:6}
    

std/templates/std/coop/include/coop_company_form.html
<div id="companyFormId" style="margin-top:5px;{% if co_op_companies %} display: none;{% endif %}">
  <div class="company-form-header-create" style="{% if co_op_company_id %}display: none;{% endif %}">
  <h3>กรอกข้อมูลหน่วยงานใหม่ {% if co_op_companies %}<a href="#" class="button small company-form-hide-links">⌃</a>{% endif %}</h3>
  สำหรับขัอมูลที่กรอกนี้ คุณสามารถเปิดให้นิสิตคนอื่นในภาควิชาใช้งานร่วมได้โดยเลือก "ต้องการแสดงให้นิสิตคนอื่นในภ่าควิชา" ด้านล่าง เมื่อนิสิตที่จะไปฝึกด้วยกันเลือกครบแล้ว สามารถปิดข้อมูลนี้จากนิสิตที่เหลือได้
  </div>
  <div class="company-form-header-edit" style="{% if not co_op_company_id %}display: none;{% endif %}">
    <h3>แก้ไขข้อมูลหน่วยงาน</h3>
    {% if not is_info_editable %}
      เนื่องจากมีการยื่นขออนุมัติไปแล้ว จะไม่สามารถแก้ไขชื่อหน่วยงานได้
    {% endif %}
  </div>
  <table class="frame_table">
    <tr>
      <td>
	<label for="id_company_name">ชื่อหน่วยงาน</label>
      </td>
      <td>
	{{ form.name }} 
	<span class="errorlist">{{ form.name.errors.as_text }}</span>
      </td>
    </tr>
    <tr>
      <td>
	<label for="id_working_address">ที่อยู่หน่วยงาน</label>
      </td>
      <td style="padding-right: 10px;">
	<span class="errorlist">{{ form.address.errors.as_text }}</span>
	{{ form.address }}
      </td>
    </tr>
    <tr>
      <td>
	<label for="id_working_number">เบอร์โทรศัพท์</label>
      </td>
      <td>
	{{ form.tel_number }} 
	<span class="errorlist">{{ form.tel_number.errors.as_text }}</span>&nbsp;
      </td>
    </tr>
    <tr>
      <td>
	<label for="id_working_fax_number">เบอร์โทรสาร</label>
      </td>
      <td>
	{{ form.fax_number }}
	<span class="errorlist">{{ form.fax_number.errors.as_text }}</span>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
	{{ form.is_public }}
	ต้องการให้แสดงหน่วยงานนี้กับนิสิตคนอื่นในภาควิชา (สามารถเปิด-ปิดได้ในภายหลัง)
      </td>
    </tr>
    <tr>
      <td colspan="2">
	<a class="button small blue create-update-company-links" {% if co_op_company_id %}style="display:none;"{% endif %} id="createCompanyLinkId" href="{% url 'std_coop_create_company' %}">เพิ่มหน่วยงานใหม่</a>
	<a class="button small blue create-update-company-links" {% if not co_op_company_id %}style="display:none;"{% endif %} id="updateCompanyLinkId" href="{% if co_op_company_id %}{% url 'std_coop_update_company' co_op_company_id %}{% endif %}">แก้ไขข้อมูล</a>
      </td>
    </tr>
  </table>
</div>
<script>
 $(function(){
   $('.create-update-company-links').click(function(){
     var url = $(this).attr('href');
     var post_data = $('#companyFormId input').serializeArray();
     post_data = post_data.concat($('#companyFormId textarea').serializeArray());
     $.post(url,
	    post_data,
	    function(data) {
	      if(data.result == 'ok') {
		location.reload();
		$('#companyFormId input').val('');
		$('#companyFormId input').removeAttr('checked');
		$('#companyFormId textarea').val('');
	      } else {
		$('#companyFormId').replaceWith(data.html);
	      }
	    });
     return false;
   });
 });
</script>

std/templates/std/coop/include/coop_form_table.html
<table class="frame_table">
  {% if student %}
    <tr>
      <td>นิสิต:</td>
      <td>{{ student.student_id }} {{ student }}</td>
    </tr>
  {% endif %}
  <tr>
    <td><label for="id_company_name">ชื่อหน่วยงาน:</label></td>
    <td>{{ company.name }}</td>
  </tr>
  <tr>
    <td>
      <label for="id_working_address">ที่อยู่หน่วยงาน</label>
    </td>
    <td>
      {{ company.address|linebreaks }}
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_working_number">เบอร์โทรศัพท์</label>
    </td>
    <td>
      {{ company.tel_number }} 
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_working_fax_number">เบอร์โทรสาร</label>
    </td>
    <td>
      {{ company.fax_number }}
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_internship_semester">ภาคการศึกษาที่ฝึก:</label>
    </td>
    <td>
      {{ form.internship_semester }}
      <span class="errorlist">{{ form.internship_semester.errors.as_text }}</span><br>
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_description">ลักษณะงาน:</label>
    </td>
    <td>
      {{ form.description }}
      <span class="errorlist">{{ form.description.errors.as_text }}</span><br>
      <span class="hint">โปรดระบุลักษณะงานที่ทำคร่าว ๆ</span>
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_signer_name">ชื่อหรือตำแหน่งที่จะทำหนังสือถึง:</label>
    </td>
    <td>
      {{ form.signer_name }}
      <span class="errorlist">{{ form.signer_name.errors.as_text }}</span><br>
      <span class="hint">โปรดระบุชื่อหรือตำแหน่งที่จะทำหนังสือถึง เช่น ผู้จัดการ, ผู้จัดการส่วนฝึกอบรม, หรือ ผู้จัดการแผนกทรัพยากรมนุษย์ เป็นต้น ไม่ต้องระบุชื่อบริษัท</span>
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_contact_person">ผู้ประสานงานการฝึกงาน:</label>
    </td>
    <td>
      {{ form.contact_person }}
      <span class="errorlist">{{ form.contact_person.errors.as_text }}</span><br>
      <span class="hint">โปรดระบุชื่อผู้ประสานงานการฝึกงานของหน่วยงาน</span>
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_contact_number">เบอร์โทรศัพท์ผู้ประสานงาน:</label> 
    </td>
    <td>
      {{ form.contact_tel_number }}
      <span class="errorlist">{{ form.contact_tel_number.errors.as_text }}</span>&nbsp;&nbsp;
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_contact_email">อีเมล์ของผู้ประสานงาน:</label>
    </td>
    <td>
      {{ form.contact_email }}
      <span class="errorlist">{{ form.contact_email.errors.as_text }}</span>
    </td>
  </tr>
  <tr>
    <td colspan="2">
      ช่วงระยะเวลาการฝึกงานสหกิจศึกษา
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_start_date">วันที่เริ่มฝึกงาน:</label>
    </td>
    <td>
      {{ form.beginning_date }}
      <span class="errorlist">{{ form.beginning_date.errors.as_text }}</span>
    </td>
  </tr>
  <tr>
    <td>
      <label for="id_end_date">วันที่สิ้นสุดการฝึกงาน:</label>
    </td>
    <td>
      {{ form.end_date }}
      <span class="errorlist">{{ form.end_date.errors.as_text }}</span>&nbsp;
    </td>
  </tr>
</table>

<script type="text/javascript">
 $(function(){
   $("#id_beginning_date").datepicker({dateFormat: "yy-mm-dd", beforeShowDay: $.datepicker.noWeekends});
   $("#id_end_date").datepicker({dateFormat: "yy-mm-dd", beforeShowDay: $.datepicker.noWeekends});
   $('#id_internship_semester option[value="1"]').text('ภาคต้น ปีการศึกษา {{ next_year }}');
   $('#id_internship_semester option[value="2"]').text('ภาคปลาย ปีการศึกษา {{ next_year|add:-1 }}');
 });
</script>

std/templates/std/coop/include/personal.html
<small>ข้อมูลด้านล่างจะส่งให้กับศูนย์สหกิจศึกษาของทางมหาวิทยาลัย กรุณาตรวจสอบอีเมลและเบอร์ติดต่อ สามารถแก้ไขได้ที่หน้า <a class="small green button" href="{% url 'std_profile' %}">ข้อมูลส่วนตัว</a></small>
<ul>
  <li>อีเมล: {{ student.email }}</li>
  <li>เบอร์ติดต่อ: {{ student.tel_no }}</li>
  <li>
    ที่อยู่:
    {% if student_detail %}
      <div class="student-address-text">
	{{ student_detail.address|linebreaksbr }}
      </div>
      <a class="medium orange button address-form-toggle-buttons" href="#">แก้ไข</a>
    {% else %}
      <a class="medium blue button address-form-toggle-buttons" href="#">เพิ่มข้อมูล</a>
    {% endif %}
    <div id="addressFormId" class="" style="display:none;">
      <form action="{% url 'std_coop_address' %}" method="post">
	<textarea name="address" rows="3" style="margin-right: 10px;">{% if student_detail %}{{ student_detail.address }}{% endif %}</textarea>
	<input type="submit" class="medium green button" value="จัดเก็บ">
      </form>
    </div>
  </li>
</ul>
<script>
 $(function(){
   $(".address-form-toggle-buttons").click(function(){
     $(this).hide();
     $('.student-address-text').hide();
     $("#addressFormId").show();
     return false;
   });
 });
</script>