regis/config/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns(
    'regis.config.views',

    url(r'^$', 'index', name='regis_config_index'),
    url(r'^update/(\d+)/$', 'update', name='regis_config_update'),
    url(r'^terms/', 'terms_edit', name='regis_config_terms'),
)

regis/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns(
    'regis.views',

    url(r'^$', 'index', name='regis_index'),
    url(r'^company/', include('regis.company.urls')),
    url(r'^student/', include('regis.student.urls')),
    url(r'^department/', include('regis.department.urls')),
    url(r'^config/', include('regis.config.urls')),
    url(r'^mail/', include('regis.mass_mailing.urls')),
)

urlpatterns += patterns(
    'regis.stats.views',
    
    url(r'^stats/details/$', 'assignment_details_by_dept' , name='regis_stat_detail'),
    url(r'^stats/$', 'assignment_stats' , name='regis_stat'),
    url(r'^stats/(\d+)/$', 'assignment_stats', name='regis_stat'),
    url(r'^stats/students/(\d+)/(\w+)$', 'show_std_list' , name='regis_show_std_list'),
    url(r'^stats/students/(\d+)/(\w+)/(\d+)/$', 'show_std_list' , name='regis_show_std_list'),

    url(r'^stats/assignments/companies/$', 'assignment_company_stats', name='regis_stats_assignments_companies'),
    url(r'^stats/assignments/companies/(\d+)/$', 'assignment_company_stats', name='regis_stats_assignments_companies'),

    url(r'^stats/coop/$', 'coop_stats_by_dept', name='regis_stats_coop'),
    url(r'^stats/coop/requests/(\d+)/(\d+)/', 'coop_report', name='regis_stats_coop_report'),
)

std/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns(
    'std.views',
    url(r'^$', 'index', name='std_index'),
    url(r'^underconst/$', 'underconst', name='std_under_construction'),

    url(r'^login/$', 'auth.login', name='std_login'),
    url(r'^login/token/$', 'auth.login_with_token', name='std_login_with_token'),
    url(r'^logout/$', 'auth.logout', name='std_logout'),

    url(r'^edit/', 'profile.edit', name='std_edit'),
    url(r'^profile/','profile.profile',name='std_profile'),
    url(r'^confirm_email/(.+)/','profile.confirm_email'),
    url(r'^regtype/(\d)/$','choose_reg_type',name='std_choose_reg_type'),
    url(r'^regtype/(\d)/confirm/','confirm_reg_type',name='std_confirm_reg_type'),

    url(r'^checkstatus/$','check_internship_status',name='std_checkstatus'),
    url(r'^print_request_form/$','PrintRequestForm',name='std_print_request_form'),

    url(r'^companies/$','company_list',name='std_company_list'),
      
    url(r'^selection/$','company_selection.list',name='std_selection_list'),
    url(r'^selection/select/(\d+)/$','company_selection.select',
        name='std_selection_select'),
    url(r'^selection/deselect/(\d+)/$','company_selection.deselect',
        name='std_selection_deselect'),

    url(r'^company/search/$', 'company.search',
        name='std_company_search'),
    url(r'^company/search/(.+)/$','company.list_by_char',name='std_company_list_by_char'),

    url(r'^self_appl/$', 'company.self_appl_index',
        name='std_self_appl_index'),
    url(r'^self_appl/confirm/$', 'company.self_appl_confirm',
        name='std_self_appl_confirm'),

    url(r'^self_appl/requests/$', 'company.new_request',
        name='std_self_appl_new_company_request'),
    url(r'^self_appl/requests/confirm/(\d+)/', 'company.request_confirm',
        name='std_self_appl_request_confirm'),
    url(r'^self_appl/requests/inactive/$', 'company.inactive_requests',
        name='std_self_appl_inactive_company_requests'),
    url(r'^self_appl/requests/print/(\d+)/$', 'company.print_request',
        name='std_self_appl_request_print'),
    url(r'^self_appl/requests/sending_letter/(\d+)/$', 'company.print_request_sending_letter_pdf',
        name='std_self_appl_print_request_sending_letter'),

    url(r'^self_appl/announcement/print/$', 'company.print_announcement',
        name='std_self_appl_request_print_announcement'),

    url(r'^self_appl/stdsearch/$', 'company.student_search',
        name='std_self_appl_student_search'),
    url(r'^self_appl/name/search/$', 'company.search_by_name_ajax',
        name='std_self_appl_company_search_by_name_ajax'),

    url(r'^self_appl/applications/create/$', 'company.create_direct_application',
        name='std_self_appl_create_application'),
    url(r'^self_appl/applications/update/(\d+)/$', 'company.update_direct_application',
        name='std_self_appl_update_application'),
    url(r'^self_appl/applications/cancel/(\d+)/$', 'company.cancel_direct_application',
        name='std_self_appl_cancel_application'),
    url(r'^self_appl/applications/print/(\d+)/$', 'company.print_direct_application_letter',
        name='std_self_appl_print_application_letter'),
    url(r'^self_appl/applications/verified/$', 'company.list_verified_direct_application_companies',
        name='std_self_appl_list_verified_companies'),
    url(r'^self_appl/applications/sending_letter/(\d+)/$', 'company.print_direct_application_sending_letter_pdf',
        name='std_self_appl_print_application_sending_letter'),
    
    url(r'^print_company_letter/(\d+)/$',
        'print_letter', name='std_print_letter'),

    url(r'^coop/$', 'coop.index',
        name='std_coop_index'),
    url(r'^coop/address/$', 'coop.update_address',
        name='std_coop_address'),

    url(r'^coop/companies/$', 'coop.update_company',
        name='std_coop_create_company'),

    url(r'^coop/companies/(?P<co_op_company_id>\d+)/$', 'coop.update_company',
        name='std_coop_update_company'),
    url(r'^coop/requests/(?P<co_op_company_id>\d+)/$', 'coop.create_request',
        name='std_coop_create_request'),

    url(r'^coop/requests/print/(\d+)/([a-z]+)/$', 'coop.print_request',
        name='std_coop_request_print'),
)

worktraining/urls.py
from django.conf.urls import url, include, patterns
from django.conf import settings

import django.contrib.staticfiles.views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import commons.views
import regis.announcement.views
import evaluations.views
import commons.auth_views

urlpatterns = patterns(
    '',
    #(r'^$',
    # 'django.views.generic.simple.direct_to_template',
    # {'template': 'front.html'}),
    url(r'^$', commons.views.index, name='front_page'),

    url(r'^announcement/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_detail,
        name='front_announcement_detail'),
    url(r'^announcement/edit/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_edit,
        name='announcement_edit'),
    url(r'^announcement/index/$',
        regis.announcement.views.list,
        name='announcement_index'),
    url(r'^announcement/create/$',
        regis.announcement.views.announcement_create,
        name='announcement_create'),
    url(r'^announcement/delete/(?P<announcement_id>\d+)/$',
        regis.announcement.views.announcement_delete,
        name='announcement_delete'),
    
    (r'^regis/', include('regis.urls')),
    (r'^std/', include('std.urls')),
    (r'^eval/', include('evaluations.urls')),
    (r'^committee/', include('committee.urls')),
    (r'^commons/', include('commons.urls')),
    (r'^direct/', include('direct_appl.urls')),

    url(r'^ev/(\d+)/(.+)/$',
        evaluations.views.edit_by_company,
        name='short_evaluations_edit_by_company'),


    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # authentication
    url(r'^accounts/login/$', 
        commons.auth_views.login,
        name='admin_login'),
    url(r'^accounts/logout/$', 
        'django.contrib.auth.views.logout',
        { 'next_page': settings.LOGOUT_URL },
        name='admin_logout'),
    url(r'^accounts/login/token/$',
        commons.auth_views.login_user_with_token,
        name='admin_login_token'),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        # Static media (for development)
        (r'^site_media/(?P<path>.*)$',
         django.contrib.staticfiles.views.serve),
    )

regis/announcement/views.py
# _*_ coding: utf-8 _*_
from django.http import HttpResponse , HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect
from django import forms

from regis.models import Announcement
from django.forms import ModelForm
from django.core.files.storage import default_storage
from django.contrib.auth.decorators import login_required

currentpage = 'web_system'

def announcement_detail(request,announcement_id):
    announcement = get_object_or_404(Announcement, pk=announcement_id)
    return render_to_response("regis/announcement/announcement_detail.html",{'announcement':announcement},
                               context_instance=RequestContext(request))

class AnnouncementForm(ModelForm):
    class Meta:
        model = Announcement
        fields = ('title', 'description','file','is_in_download_section')

@login_required
def announcement_edit(request,announcement_id):
    announcement = get_object_or_404(Announcement, pk=announcement_id)
    oldpath = announcement.file
    if request.method == 'POST':
        form = AnnouncementForm(request.POST, request.FILES, instance=announcement)
        if form.is_valid():
            form.save()
            if request.FILES and oldpath:
                default_storage.delete(oldpath)
            return HttpResponseRedirect(reverse('front_announcement_detail',kwargs={'announcement_id':announcement.id}))
    else:
        form = AnnouncementForm(instance=announcement)

    return render_to_response("regis/announcement/announcement_edit.html",
                              {'form':form ,
                               'announcement':announcement,
                               'currentpage':currentpage },
                               context_instance=RequestContext(request))

@login_required
def list(request):
    announcements = Announcement.objects.all()
    return render_to_response("regis/announcement/index.html",
                              {'announcements': announcements,
                               'currentpage':currentpage},
                              context_instance=RequestContext(request))

@login_required    
def announcement_create(request):
    if request.method == 'POST':
       form = AnnouncementForm(request.POST, request.FILES)
       if form.is_valid():
           announcement = Announcement()
           if request.FILES:
               announcement.file = request.FILES['file']         
           announcement.title = form.cleaned_data['title']
           announcement.description = form.cleaned_data['description']
           announcement.is_in_download_section = form.cleaned_data['is_in_download_section']
           announcement.save()
           return HttpResponseRedirect(reverse('announcement_index'))
    else:
        form = AnnouncementForm()
        
    return render_to_response('regis/announcement/announcement_create.html',
                              { 'form': form ,
                               'currentpage':currentpage},
                              context_instance=RequestContext(request))

@login_required   
def announcement_delete(request,announcement_id):
    announcement = Announcement.objects.get(id = announcement_id)
    announcement.delete()
    return HttpResponseRedirect(reverse('announcement_index')) 
        
    

regis/config/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from commons.models import Configuration
from commons.decorators import sa_admin_required
from regis.models import Conditions
from django.forms import ModelForm

currentpage = 'web_system'


@sa_admin_required
def index(request):
    configs = Configuration.objects.all()

    return render_to_response('regis/config/index.html',
                              { 'configs': configs ,
                                'currentpage':currentpage},
                              context_instance=RequestContext(request))

@sa_admin_required
def update(request,config_id):
    config = get_object_or_404(Configuration,pk=config_id)
    config.value = request.POST['value']
    v = config.get_value()
    config.set_value(v)
    config.save()

    return HttpResponseRedirect(reverse('regis_config_index'))

class ConditionsForm(ModelForm):
    class Meta:
        model = Conditions
        fields = ['detail']

def terms_edit(request):
    if request.method == 'POST':
        form = ConditionsForm(request.POST)
        if form.is_valid():
            try:
                conditions = Conditions.objects.all()[0]
            except IndexError:
                conditions = Conditions()

            conditions.detail = form.cleaned_data['detail']
            conditions.save()
            return HttpResponseRedirect(reverse('regis_config_index'))

    else:
        try:
            conditions = Conditions.objects.all()[0]
            form = ConditionsForm(instance=conditions)
        except IndexError:
            form = ConditionsForm()

    return render_to_response('regis/config/terms_edit.html', {'form': form}, context_instance=RequestContext(request))

regis/mass_mailing/views.py
# -*- coding: utf-8 -*-
from django import forms
from django.shortcuts import render_to_response
from django.template import RequestContext

from commons.academia import get_next_worktraining_year
from commons.decorators import sa_admin_required
from commons.email import send_mail_to_student, send_mail
from regis.models import Student, Department
from commons.models import Configuration

class EmailForm(forms.Form):
    start_year = 2553
    end_year = get_next_worktraining_year()
    if start_year < end_year - 2:
        start_year = end_year - 2
    YEAR_CHOICE = []
    for year in range(start_year,end_year+1):
        YEAR_CHOICE.append([year,year])
    YEAR_CHOICE.reverse()
    year = forms.ChoiceField(choices=YEAR_CHOICE,
                             label=u'ปีที่เข้าฝึกงาน')
    dept_choices = ([(0,'ทุกสาขาวิชา')] +
                    [(d.id,d.name) for d in
                     Department.objects.order_by('name').all() if not d.is_hidden])
    department = forms.MultipleChoiceField(label=u'สาขาวิชา',
                                           required=True,
                                           choices=dept_choices,
                                           widget=forms.CheckboxSelectMultiple(attrs={'class':'department_choices'}))
    subject = forms.CharField(label=u'หัวเรื่อง',
                              required=True,
                              widget=forms.TextInput(attrs={'size':'50'}))
    body = forms.CharField(label=u'เนื้อหา',
                           required=True,
                           widget=forms.Textarea)

@sa_admin_required
def index(request):
    notice = ''
    if request.method=='POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            body = form.cleaned_data['body']
            department_ids = [int(x) for x in form.cleaned_data['department']]

            year = int(form.cleaned_data['year'])

            if 0 in department_ids:
                department = None
                students = Student.all_registered_for_year(year, department)
            else:
                students = []
                for d in department_ids:
                    department = Department.objects.get(pk=d)
                    students += Student.all_registered_for_year(year, department)

            cc_emails = Configuration.get('email.cc_emails')
            if cc_emails:
                for email in cc_emails.split(','):
                    email = email.strip()
                    if email != '':
                        send_mail(email, subject + u' (สำเนา)', body)

            count = 0
            for s in students:
                #print s.student_id
                send_mail_to_student(s, subject, body)
                count += 1

            notice = u'ส่งเมล์ไปยังนิสิตจำนวน %d คนแล้ว' % count
            form = EmailForm()

    else:
        form = EmailForm()

    return render_to_response("regis/mass_mailing/index.html",
                              { 'form': form,
                                'notice': notice },
                              context_instance=RequestContext(request))

regis/templates/regis/department/detail.html
{% extends "regis/base.html" %}

{% block content %}
{% include "regis/include/department_header.html" %}
{% include "regis/include/department_menu.html" %}
<p>กรุณาเลือกแสดงข้อมูลนิสิตจากรายการด้านบน</p>
<div id="clear"></div>
{% endblock content %}

regis/templates/regis/department/detail_assigned_std.html
{% extends "regis/base.html" %}

{% block content %}
  {% include "regis/include/department_header.html" %}
  {% include "regis/include/department_menu.html" %}
  <h1>รายชื่อนิสิตทั้งหมดในภาควิชาที่ได้ที่ฝึกงานแล้ว ({{total_std}} คน)</h1>
  
  <ol id="pagination">
    <li id="pagination-title">หน้ารายงาน:</li> 
    {% for i in pages %}
      <li {% if page_number ==  i %}class="selected">{{i}}{% else %}>
        <a href="{% url 'regis_department_assigned_std' department.code year i  %}">{{i}}</a>
      {% endif %}
      </li>
    {% endfor %}
  </ol>
  <div style="float: right;">
    <a class="small button" href="{% url 'regis_department_assigned_std_list_report' department.code year %}">ดาวน์โหลดรายการนิสิต (ใบเซ็นต์ชื่อ)</a>
  </div>

  <div style="clear: both;"></div>
  <br/>

  <form id="year_form_id" action="{% url 'regis_department_assigned_std' department.code year 1  %}" method="POST">
    <span id="header_text">แสดงรายชื่อนิสิตในปีการศึกษา {{ form.year }}</span>
    <input type="submit" value="แสดง"/>
  </form>
  <table cellpadding="2" class="info_list">
    <tr class="header">
      <th>รหัสนิสิต</th>
      <th>ชื่อ-นามสกุล</th>
      {% if shows_departments %}
        <th>ภาควิชา</th>
      {% endif %}
      <th>ประเภทการสมัคร</th>
      <th>สถานประกอบการ</th>
    </tr>
    {% for student in assigned_students %}
      <tr class="{% cycle 'odd' 'even' %}">
        <td><a href="{% url 'student_detail' student.student_id %}">{{ student.student_id }}</a></td>
        <td>{{ student.full_name }}</td>
        {% if shows_departments %}
          <td>{{ student.department }}</td>
        {% endif %}
        <td class="center">
          {{ student.registration_type }}
        </td>
        <td>
          {% if student.assignment %}
            {% if student.assignment.is_self_application %}
              {{ student.assignment.get_company_name }}
            {% else %}
              <a href="{% url 'regis_company_detail' student.assignment.company_id %}">{{ student.assignment.company }}</a>
            {% endif %}
          {% else %}
            {{ student.assigned_company }}
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </table>
  <div style="clear: both;"></div>
  <script type="text/javascript">
    function updateAction() {
      var st = "{% url 'regis_department_assigned_std' department.code 99999 1 %}";
      st = st.replace("99999",$("#id_year").val());
      $("#year_form_id").attr("action",st);				           
    }
    $(function() {
      updateAction();
      $("#id_year").click(function() {
	updateAction();
      });
    });
  </script>
{% endblock content %}

regis/templates/regis/department/detail_listall_std.html
{% extends "regis/base.html" %}

{% block content %}
  {% include "regis/include/department_header.html" %}
  {% include "regis/include/department_menu.html" %}
  <h1>รายชื่อนิสิตทั้งหมดในภาควิชา ({{total_std}} คน)</h1>
  <ol id="pagination">
    <li id="pagination-title">page</li> 
    {% for i in pages %}
      <li {% if page_number ==  i %}class="selected">{{i}}{% else %}>
        <a href="{% url 'regis_department_listall_std' department.code i %}">{{i}}</a>
      {% endif %}
      </li>
    {% endfor %}
  </ol>
  <div style="float: right;">
    {% if not is_committee %}
      <a class="small button" target="_blank" href="{% url 'regis_department_all_std_label_report' department.code next_year %}">ดาวน์โหลดเลเบล</a>
    {% endif %}
  </div>
  
  <div style="clear: both;"></div>
  <br/>	
  <table class="info_list" cellpadding="2">
    <tr class="header">
      <th>รหัสนิสิต</th>
      <th>ชื่อ-นามสกุล</th>
      <th>บริษัท</th>
    </tr>
    {% for student in students %}
      <tr class="{% cycle 'odd' 'even' %}">
        <td><a href="{% url 'student_detail' student.student_id %}">{{ student.student_id }}</a></td>
        <td>{{student.full_name}}</td>
        <td>{{student.intern_company_for_current_year }}</td>
      </tr>
    {% endfor %}
  </table>
  </div>
  <div style="clear: both;"></div>
{% endblock content %}

regis/templates/regis/department/detail_no_evaluation.html
{% extends "regis/base.html" %}

{% block content %}
{% include "regis/include/department_header.html" %}
{% include "regis/include/department_menu.html" %}
<h1>รายชื่อนิสิตทั้งหมดในภาควิชาที่ยังไม่ได้ใบประเมินตอบกลับ ({{total_std}} คน)</h1>	
<ol id="pagination">
<li id="pagination-title">page</li> 
{% for i in pages %}
	<li {% if page_number ==  i %}class="selected">{{i}}{% else %}>
		<a href="{% url 'regis_department_no_evaluation' department.code year i %}">{{i}}</a>
		{% endif %}
	</li>
{% endfor %}
</ol>
<div id="clear"></div>
<br/>
<form id="year_form_id" action="{% url 'regis_department_no_evaluation' department.code year 1 %}" method="POST">
    <span id="header_text">แสดงรายชื่อนิสิตที่ฝึกงานในปี {{ form.year }}</span>
    <input type="submit" value="แสดง"/>
<form>
<br/>	
<table cellpadding="2" class="info_list">
  <tr class="header">
    <th>ลำดับที่</th>
    <th>รหัสนิสิต</th>
    <th>ชื่อ-นามสกุล</th>
    <th>บริษัท</th>
  </tr>
  {% for student in students %}
    <tr class="{% cycle 'odd' 'even' %}">
      <td>{{forloop.counter}}</td>
      <td><a href="{% url 'student_detail' student.student_id %}">{{ student.student_id }}</a></td>
      <td>{{student.full_name}}</td>
      <td>
        {% if student.intern_company %}
          <a href="{% url 'regis_company_detail' student.intern_company.id %}">{{ student.intern_company }}</a>
	{% else %}
          {% if student.assignment.is_self_application %}
            {{ student.assignment.get_company_name }}
          {% else %}
	    ยังไม่ได้รับการคัดเลือกเข้าฝึกงานกับสถานประกอบการ
          {% endif %}
	{% endif %}
      </td>
    </tr>
    {% endfor %}
</table>
</div>
<div id="clear">
<script type="text/javascript">
  function updateAction() {
	  var st = "{% url 'regis_department_no_evaluation' department.code 99999 1 %}";
	  st = st.replace("99999",$("#id_year").val());
	  $("#year_form_id").attr("action",st);				           
  }
  $(function() {
	  updateAction();
	  $("#id_year").click(function() {
		  updateAction();
	  });
  });
</script>
{% endblock content %}

regis/templates/regis/department/detail_registered_std.html
{% extends "regis/base.html" %}

{% block content %}
{% include "regis/include/department_header.html" %}
{% include "regis/include/department_menu.html" %}
<div style="float:right"><a class="button green small" href="{% url 'export_csv_dep' department.code %}">Export to csv</a></div>
<h1>รายชื่อนิสิตทั้งหมดที่สมัครขอเข้าฝึกงาน ({{total_std}} คน)</h1> 
{% if under_credit_students %}
  มีนิสิตจำนวน {{ under_credit_students|length }} คนที่หน่วยกิตไม่ถึงที่กำหนด มีสรุปรายชื่ออยู่ท้ายรายการ
{% endif %}
<div id="clear"></div><br/>	

<div class="form-section">
<b>จำนวนแยกตามประเภท:</b>
{% for r in regtype_counts %}
  {{ r.label }} {{ r.count }} คน, 
{% endfor %}
รวม {{ total_std }} คน<br/>
</div>

<table class="info_list" cellpadding="2">
  <tr class="header">
    <th></th>
    <th>รหัสนิสิต</th>
    <th>ชื่อ-นามสกุล</th>
    <th>บริษัท</th>
    <th>หน่วยกิตรวม</th>
    <th>ประเภทการสมัคร</th>
  </tr>
  {% for student in students %}
    <tr class="{% cycle "even" "odd" %}">
      <td>{{ forloop.counter }}</td>
      <td><a href="{% url 'student_detail' student.student_id %}">{{ student.student_id }}</a></td>
      <td>{{ student.full_name }}</td>
      <td>{{ student.intern_company_for_current_year|default_if_none:'-' }}</td>
      <td>
        {{ student.current_credits|default_if_none:"-" }}
        {% if not student.is_eligible_to_apply %}
          <span class="info-tag red">ไม่ผ่านเกณฑ์</span>
        {% endif %}
      </td>
      <td>
        {{ student.current_status.registration_type_display }}
      </td>
    </tr>
  {% endfor %}
</table>


{% if under_credit_students %}
  <h1>นิสิตที่หน่วยกิตไม่ถึงเกณฑ์ ({{ under_credit_students|length }} คน)</h1>
  <table class="info_list" cellpadding="2">
    <tr class="header">
      <th></th>
      <th>รหัสนิสิต</th>
      <th>ชื่อ-นามสกุล</th>
      <th>บริษัท</th>
      <th>หน่วยกิตรวม</th>
    </tr>
    {% for student in under_credit_students %}
      <tr class="{% cycle "even" "odd" %}">
        <td>{{ forloop.counter }}</td>
        <td>{{ student.student_id }}</td>
        <td>{{ student.full_name }}</td>
        <td>{{ student.intern_company_for_current_year }}</td>
        <td>
          {{ student.current_credits|default_if_none:"-" }}
        </td>
      </tr>
    {% endfor %}
  </table>
{% endif %}
</div>
{% endblock content %}

regis/templates/regis/department/detail_unassigned_std.html
{% extends "regis/base.html" %}

{% block content %}
{% include "regis/include/department_header.html" %}
{% include "regis/include/department_menu.html" %}
<h1>รายชื่อนิสิตทั้งหมดในภาควิชาที่ยังไม่ได้ที่ฝึกงาน ({{total_std}} คน)</h1>
<ol id="pagination">
<li id="pagination-title">page</li> 
{% for i in pages %}
	<li {% if page_number ==  i %}class="selected">{{i}}{% else %}>
		<a href="{% url 'regis_department_unassigned_std' department.code year i  %}">{{i}}</a>
		{% endif %}
	</li>
{% endfor %}


</ol>

<div id="clear"></div>
<br/>
<form id="year_form_id" action="{% url 'regis_department_unassigned_std' department.code year 1  %}" method="POST">
  <span id="header_text">แสดงรายชื่อนิสิตในปีการศึกษา {{ form.year }}</span>
  <input type="submit" value="แสดง"/>
</form>
<table class="info_list" cellpadding="2">
  <tr class="header">
    <th></th>
    <th>รหัสนิสิต</th>
    <th>ชื่อ-นามสกุล</th>
    <th>ประเภทการสมัคร</th>
  </tr>
  {% for student in unassigned_students %}
    <tr class="{% cycle 'odd' 'even' %}">
      <td>{{ student.number }}</td>
      <td><a href="{% url 'student_detail' student.student_id %}">{{ student.student_id }}</a></td>
      <td>{{ student.full_name }}</td>
      <td class="center">{{ student.registration_type_for_next_year }}</td>
    </tr>
  {% endfor %}
</table>
<script type="text/javascript">
 function updateAction() {
   var st = "{% url 'regis_department_unassigned_std' department.code 99999 1 %}";
   st = st.replace("99999",$("#id_year").val());
   $("#year_form_id").attr("action",st);				           
 }
 $(function() {
   updateAction();
   $("#id_year").click(function() {
     updateAction();
   });
 });
</script>
{% endblock content %}

regis/templates/regis/department/list.html
{% extends "regis/base.html" %}
{% block content %}
  <h1>รายชื่อภาควิชา</h1>
  <table>
    {% for department in departments %}
      <tr>
	<td><a href="{% url 'regis_department_detail' department.code %}">{{department.code }} : {{department.name}}</a></td>
      </tr>
    {% endfor %}
  </table>
{% endblock content %}